# Test functions on 2D arrays

Wed Nov 21, 2018

In [16]:
import array_spiral as spiral
import numpy as np

In [3]:
%load_ext autoreload
%autoreload 2

In [6]:
arr = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

print(list(spiral.array_spiral(arr))) #Output should be [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]


In [7]:
for x in spiral.array_spiral(arr): print(x)

1
2
3
4
8
12
11
10
9
5
6
7


In [9]:
arr = [[1,2]]
for x in spiral.array_spiral(arr): print(x)

1
2


In [10]:
arr = [[1],[2]]
for x in spir.array_spiral(arr): print(x)

1
2


In [22]:
a = np.arange(9*6).reshape(9,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

In [20]:
print([x for x in spiral.array_spiral(a)])

[0, 1, 2, 3, 4, 5, 11, 17, 23, 29, 35, 41, 47, 53, 52, 51, 50, 49, 48, 42, 36, 30, 24, 18, 12, 6, 7, 8, 9, 10, 16, 22, 28, 34, 40, 46, 45, 44, 43, 37, 31, 25, 19, 13, 14, 15, 21, 27, 33, 39, 38, 32, 26, 20]


In [14]:
a[1,2]

8

In [15]:
a[1][2] #Is there a difference between this way of indexing vs. a[1,2]?

8

In [18]:
print([x for x in spiral.array_spiral(arr)])

[1, 2]


In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

## New version fails when array is

1. A single row of length > 2
2. A single column of length >2
3. A 1x1 array

In [44]:
print([x for x in spiral.array_spiral(np.arange(5).reshape(1,5))])

[0, 1, 2, 3, 4, 3, 2, 1]


In [45]:
print([x for x in spiral.array_spiral(np.arange(5).reshape(5,1))])

[0, 1, 2, 3, 4, 3, 2, 1]


In [48]:
print([x for x in spiral.array_spiral([[78]])])

[]


## Test original version I wrote

In [24]:
b = np.arange(3*4).reshape(3,4) + 1
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print([x for x in spiral.array_spiral(b)]) #better version

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]


In [26]:
print([x for x in spiral.array_spiral_orig(b)]) #Hmm, has a bug... repeats the last upstroke

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7, 6]


In [27]:
b = np.arange(3*5).reshape(3,5) + 1
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
print([x for x in spiral.array_spiral(b)]) #better version
print([x for x in spiral.array_spiral_orig(b)])

[1, 2, 3, 4, 5, 10, 15, 14, 13, 12, 11, 6, 7, 8, 9, 8]
[1, 2, 3, 4, 5, 10, 15, 14, 13, 12, 11, 6, 7, 8, 9, 8, 7]


In [30]:
b.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [31]:
print([x for x in spiral.array_spiral(b.reshape(5,3))]) #better version
print([x for x in spiral.array_spiral_orig(b.reshape(5,3))])

[1, 2, 3, 6, 9, 12, 15, 14, 13, 10, 7, 4, 5, 8, 11, 8]
[1, 2, 3, 6, 9, 12, 15, 14, 13, 10, 7, 4, 5, 8, 11, 8]


In [32]:
b = np.arange(3*4).reshape(4,3) + 1
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
print([x for x in spiral.array_spiral(b)]) #better version
print([x for x in spiral.array_spiral_orig(b)])

[1, 2, 3, 6, 9, 12, 11, 10, 7, 4, 5, 8]
[1, 2, 3, 6, 9, 12, 11, 10, 7, 4, 5, 8]


In [36]:
print([x for x in spiral.array_spiral([[1,2]])]) #better version
print([x for x in spiral.array_spiral_orig([[1,2]])])

[1, 2]
[1, 2, 1]


In [37]:
print([x for x in spiral.array_spiral([[1,2,3]])]) #better version
print([x for x in spiral.array_spiral_orig([[1,2,3]])])

[1, 2, 3, 2]
[1, 2, 3, 2, 1]


### Oops, looks like the "correct" version above also has a bug...

In [38]:
print([x for x in spiral.array_spiral([[1,2,3,4]])]) #better version
print([x for x in spiral.array_spiral_orig([[1,2,3,4]])])

[1, 2, 3, 4, 3, 2]
[1, 2, 3, 4, 3, 2, 1]


In [39]:
b = np.arange(4).reshape(4,1) + 1
print([x for x in spiral.array_spiral(b)]) #better version
print([x for x in spiral.array_spiral_orig(b)])

[1, 2, 3, 4, 3, 2]
[1, 2, 3, 4, 3, 2]


In [41]:
c = [[1],[2],[3],[4]]
print([c[i][0] for i in range(len(c))])

[1, 2, 3, 4]


In [42]:
print([x[0] for x in c])

[1, 2, 3, 4]
