# Test functions on 2D arrays

Wed Nov 21, 2018

In [152]:
import array_spiral as spiral
import numpy as np

In [153]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [154]:
arr = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

print(list(spiral.array_spiral(arr))) #Output should be [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]


In [155]:
for x in spiral.array_spiral(arr): print(x)

1
2
3
4
8
12
11
10
9
5
6
7


In [156]:
arr = [[1,2]]
for x in spiral.array_spiral(arr): print(x)

1
2


In [157]:
arr = [[1],[2]]
for x in spir.array_spiral(arr): print(x)

1
2


In [158]:
a = np.arange(9*6).reshape(9,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

In [159]:
print([x for x in spiral.array_spiral(a)])

[0, 1, 2, 3, 4, 5, 11, 17, 23, 29, 35, 41, 47, 53, 52, 51, 50, 49, 48, 42, 36, 30, 24, 18, 12, 6, 7, 8, 9, 10, 16, 22, 28, 34, 40, 46, 45, 44, 43, 37, 31, 25, 19, 13, 14, 15, 21, 27, 33, 39, 38, 32, 26, 20]


In [160]:
a[1,2]

8

In [161]:
a[1][2] #Is there a difference between this way of indexing vs. a[1,2]?

8

In [162]:
print([x for x in spiral.array_spiral(arr)])

[1, 2]


In [163]:
np.arange(5)

array([0, 1, 2, 3, 4])

### Without the if statements handling single rows or columns, the new version originally failed when array was:

1. A single row of length > 2
2. A single column of length >2
3. A 1x1 array

### Now this should be fixed:

In [164]:
print([x for x in spiral.array_spiral(np.arange(5).reshape(1,5))])

[0, 1, 2, 3, 4]


In [165]:
spiral.array_spiral(np.arange(5).reshape(1,5))

<generator object array_spiral at 0x10ddf13b8>

In [166]:
list(spiral.array_spiral(np.arange(5).reshape(1,5)))

[0, 1, 2, 3, 4]

In [167]:
list(col for col in np.arange(5).reshape(1,5)[0])

[0, 1, 2, 3, 4]

In [168]:
print([x for x in spiral.array_spiral(np.arange(5).reshape(5,1))])

[0, 1, 2, 3, 4]


In [169]:
print([x for x in spiral.array_spiral([[78]])])

[78]


In [170]:
print([x for x in spiral.array_spiral([[]])]) #Good, it works on an empty 2d-array, too

[]


In [171]:
print([x for x in spiral.array_spiral([[],[],[],[]])]) #And it even works on an array of empty arrays!

[]


## Test the new version on more inputs, with varying parities

In [172]:
a = np.arange(2*2).reshape(2,2)+1
print(a, '\n')
print([x for x in spiral.array_spiral(a)])

[[1 2]
 [3 4]] 

[1, 2, 4, 3]


In [173]:
print([x for x in spiral.array_spiral(a)])

[1, 2, 4, 3]


In [174]:
a = np.arange(3*3).reshape(3,3)+1
print(a, '\n')
print([x for x in spiral.array_spiral(a)])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1, 2, 3, 6, 9, 8, 7, 4, 5]


### Oh crap. It didn't work if there was a central element. But now it's fixed!

In [175]:
a = np.arange(5*5).reshape(5,5)+1
print(a, '\n')
print([x for x in spiral.array_spiral(a)])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[1, 2, 3, 4, 5, 10, 15, 20, 25, 24, 23, 22, 21, 16, 11, 6, 7, 8, 9, 14, 19, 18, 17, 12, 13]


In [176]:
a = np.arange(2*3).reshape(2,3)+1
print(a, '\n')
print([x for x in spiral.array_spiral(a)])

[[1 2 3]
 [4 5 6]] 

[1, 2, 3, 6, 5, 4]


In [177]:
a = np.arange(4*4).reshape(4,4)+1
print(a, '\n')
print([x for x in spiral.array_spiral(a)])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[1, 2, 3, 4, 8, 12, 16, 15, 14, 13, 9, 5, 6, 7, 11, 10]


## Test original version I wrote

In [178]:
b = np.arange(3*4).reshape(3,4) + 1
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [179]:
print([x for x in spiral.array_spiral(b)]) #Correct version (hopefully!)

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]


In [180]:
print([x for x in spiral.array_spiral_orig(b)]) #Hmm, has a bug... repeats the last upstroke

[1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7, 6]


In [181]:
b = np.arange(3*5).reshape(3,5) + 1
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [182]:
print([x for x in spiral.array_spiral(b)]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig(b)])

[1, 2, 3, 4, 5, 10, 15, 14, 13, 12, 11, 6, 7, 8, 9, 8]
[1, 2, 3, 4, 5, 10, 15, 14, 13, 12, 11, 6, 7, 8, 9, 8, 7]


In [183]:
b.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [184]:
print([x for x in spiral.array_spiral(b.reshape(5,3))]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig(b.reshape(5,3))])

[1, 2, 3, 6, 9, 12, 15, 14, 13, 10, 7, 4, 5, 8, 11, 8]
[1, 2, 3, 6, 9, 12, 15, 14, 13, 10, 7, 4, 5, 8, 11, 8]


In [185]:
b = np.arange(3*4).reshape(4,3) + 1
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [186]:
print([x for x in spiral.array_spiral(b)]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig(b)])

[1, 2, 3, 6, 9, 12, 11, 10, 7, 4, 5, 8]
[1, 2, 3, 6, 9, 12, 11, 10, 7, 4, 5, 8]


In [194]:
b = np.arange(4*6).reshape(4,6) + 1
print(b, '\n')
print([x for x in spiral.array_spiral(b)])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] 

[1, 2, 3, 4, 5, 6, 12, 18, 24, 23, 22, 21, 20, 19, 13, 7, 8, 9, 10, 11, 17, 16, 15, 14]


In [187]:
print([x for x in spiral.array_spiral([[1,2]])]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig([[1,2]])])

[1, 2]
[1, 2, 1]


In [188]:
print([x for x in spiral.array_spiral([[1,2,3]])]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig([[1,2,3]])])

[1, 2, 3]
[1, 2, 3, 2, 1]


### Oops, looks like the "correct" version above also has a bug... but now it's fixed!

Hopefully we won't find any more bugs... But we did! For odd square matrices (see above). Any more? Yep, the "fix" broke my code for even square matrices. Let's try again (see above).

In [189]:
print([x for x in spiral.array_spiral([[1,2,3,4]])]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig([[1,2,3,4]])])

[1, 2, 3, 4]
[1, 2, 3, 4, 3, 2, 1]


In [190]:
b = np.arange(4).reshape(4,1) + 1
print([x for x in spiral.array_spiral(b)]) #Correct version (hopefully!)
print([x for x in spiral.array_spiral_orig(b)])

[1, 2, 3, 4]
[1, 2, 3, 4, 3, 2]


In [191]:
c = [[1],[2],[3],[4]]
print([c[i][0] for i in range(len(c))])

[1, 2, 3, 4]


In [192]:
print([x[0] for x in c])

[1, 2, 3, 4]


In [193]:
spiral.test_spiral()

AssertionError: 

In [203]:
%run /Users/ndbs/anaconda3/lib/python3.6/site-packages/pytest ./array_spiral.py

============================================= test session starts =============================================
platform darwin -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/ndbs/projects/python-practice/2d-arrays, inifile:
collected 2 items

array_spiral.py FF

================================================== FAILURES ===================================================
_________________________________________________ test_spiral _________________________________________________

    def test_spiral():
        spiral = array_spiral
    
        a = np.arange(12).reshape(3,4) + 1
        assert list(spiral(a)) == [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7]
    
        a = np.arange(2*3).reshape(2,3)+1
        assert list(spiral(a)) == [1, 2, 3, 6, 5, 4]
    
        assert list(spiral([[]])) == []
    
        assert list(spiral([[], [], []])) == []
    
        assert list(spiral([[45]])) == [45]
    
        assert list(spiral([[1,2]])) == [1,2]
    
        a

SystemExit: 1

In [204]:
%tb

SystemExit: 1