# Test the `array_rotate` function

Tue Dec 4, 2018

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import array_rotate as ar

In [3]:
import numpy as np

In [4]:
a = np.arange(4*4).reshape(4,4) + 1
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
rotated = ar.rotate_square_array(a)
rotated = np.array(rotated).reshape(4,4)
print(rotated)

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]


In [11]:
a = np.arange(5*5).reshape(5,5) + 1
rotated = ar.rotate_square_array(a)
rotated = np.array(rotated).reshape(5,5)

print(a, "\n")
print(rotated)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[[21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]
 [25 20 15 10  5]]


In [18]:
ar.rotate_square_array([['x']])

[['x']]

In [19]:
ar.rotate_square_array([['a', 'b'], ['c','d']])

[['c', 'a'], ['d', 'b']]

In [17]:
ar.rotate_square_array([[]])

[[]]

In [24]:
a = np.arange(5*5).reshape(5,5) + 1
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
ar.rotate_square_array_inplace(a)
print(a)

[[21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]
 [25 20 15 10  5]]


In [26]:
ar.rotate_square_array_inplace(a)
print(a)

[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [27]:
ar.rotate_square_array_inplace(a)
print(a)

[[ 5 10 15 20 25]
 [ 4  9 14 19 24]
 [ 3  8 13 18 23]
 [ 2  7 12 17 22]
 [ 1  6 11 16 21]]


In [28]:
ar.rotate_square_array_inplace(a)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
b = np.arange(4*4).reshape(4,4) + 1
print(b, "\n")

ar.rotate_square_array_inplace(b)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[13  9  5  1]
 [14 10  6  2]
 [15 11  7  3]
 [16 12  8  4]]
